from pathlib import Path
import json,sys
r=Path(__file__).resolve().parents[1]
resources=r/'resources'
s=[]
for id in ['xiaomi.rc003','unicom.sample-28']:
 m=json.loads((resources/'remotes'/id/'model.json').read_text(encoding='utf8'))
 m={k:m[k] for k in ['schema','id','revision','family','matches','keys','raw','map_crc']}
 for k in m['keys']:k.pop('label',None)
 s.append(json.dumps(json.dumps(m,ensure_ascii=False,separators=(',',':')),ensure_ascii=False))
target=r/'firmware/esp32s3/main/catalog/buddy_models_builtin.c'
content='#include "buddy_models.h"\n/* Generated by tools/generate_models.py; do not edit. */\nconst char *const buddy_builtin_models[2] = {\n'+',\n'.join(s)+'\n};\n'
if '--check' in sys.argv:
 assert target.read_text(encoding='utf8')==content,'builtin model table is stale; run tools/generate_models.py'
else:target.write_text(content,encoding='utf8')

# Default actions are data shared with the independently buildable desktop app.
standard=json.loads((resources/'standard-keys.json').read_text(encoding='utf8'))
assert standard['version']==1
keys=standard['keys']
assert len({k['id'] for k in keys})==len(keys)
assert all(0<k['id']<64 and len(k['default'])==3 for k in keys)
target=r/'firmware/esp32s3/main/runtime/buddy_standard_bindings.inc'
content='/* Generated by tools/generate_models.py; do not edit. */\nstatic const buddy_binding_t buddy_standard_bindings[BUDDY_KEYS] = {\n'
content+=''.join('  [%d] = {%d, %d, %d},\n' % (k['id'], *k['default']) for k in keys)
content+='};\n'
if '--check' in sys.argv:
 assert target.read_text(encoding='utf8')==content,'standard bindings are stale; run tools/generate_models.py'
else:target.write_text(content,encoding='utf8')

def generated(path,content):
 target=r/path
 if '--check' in sys.argv:
  assert target.read_text(encoding='utf8')==content, str(path)+' is stale; run tools/generate_models.py'
 else: target.write_text(content,encoding='utf8')
bindings=json.loads((resources/'bindings.json').read_text(encoding='utf8'))
assert bindings['version']==1 and [v['id'] for v in bindings['kinds']]==list(range(7))
content='/* Generated from resources/bindings.json; do not edit. */\n'
content+='typedef struct {bool voice,zero_mod,mod_only; uint16_t min,max;} buddy_binding_rule_t;\nstatic const buddy_binding_rule_t buddy_binding_rules[] = {\n'
for k in bindings['kinds']:content+='  {%d,%d,%d,%d,%d},\n'%(k['voiceOnly'],k['zeroModifiers'],k['modifierOnly'],k['min'],k['max'])
content+='};\n'
for k in bindings['kinds']:
 content+='_Static_assert(BM_%s == %d, "binding ABI");\n'%(k['name'].upper().replace('-','_'),k['id'])
for name,preset in bindings['voicePresets'].items():
 content+='static const buddy_binding_t buddy_voice_%s = {%d,%d,%d};\n'%(name,*preset['binding'])
content+='static buddy_binding_t buddy_voice_shortcut(buddy_binding_t b) {\n'
for name,preset in bindings['voicePresets'].items():
 if preset['binding'][0]==5:
  content+=' if(b.value==buddy_voice_%s.value)return (buddy_binding_t){%d,%d,%d};\n'%(name,*preset['shortcut'])
content+=' return (buddy_binding_t){0};}\n'
generated('firmware/esp32s3/main/runtime/buddy_binding_rules.inc',content)
protocols=json.loads((resources/'voice-protocols.json').read_text(encoding='utf8'))
assert protocols['version']==1
content='/* Generated from resources/voice-protocols.json; do not edit. */\n'
content+='typedef struct {uint8_t id,type,properties;} voice_report_rule_t;\n'
for p in protocols['protocols']:
 content+='static const voice_report_rule_t voice_reports_%d[] = {\n'%p['family']
 for v in p['reports']:content+='  {%d,%d,%d},\n'%(v['id'],v['type'],v['properties'])
 content+='};\n'
content+='static unsigned voice_report_rules(unsigned family,const voice_report_rule_t **out) {\n switch(family){\n'
for p in protocols['protocols']:content+=' case %d:*out=voice_reports_%d;return %d;\n'%(p['family'],p['family'],len(p['reports']))
content+=' default:*out=NULL;return 0;}}\n'
content+='static unsigned protocol_min_mtu(unsigned family){switch(family){\n'
for p in protocols['protocols']:content+=' case %d:return %d;\n'%(p['family'],p['mtu'])
content+=' default:return 0;}}\n'
for p in protocols['protocols']:
 for c in p['characteristics']:
  suffix=int(c['uuid'][4:8],16)
  content+='\n#define VOICE_ATVV_%d_PROPERTIES %d\n'%(suffix,c['properties'])
atvv=protocols['protocols'][0]
for name,value in [('svc',atvv['evidenceServices'][0])]+[(('tx' if c['uuid'][4:8]=='0002' else 'ctl' if c['uuid'][4:8]=='0004' else 'audio'),c['uuid']) for c in atvv['characteristics']]:
 content+='\nstatic const uint8_t k_atvv_%s_uuid[16] = {%s};\n'%(name,','.join('0x%02x'%v for v in bytes.fromhex(value.replace('-',''))[::-1]))
generated('firmware/adapters/rc003/voice_protocol_rules.inc',content)

wire=json.loads((resources/'catalog-wire.json').read_text(encoding='utf8'))
assert wire['version']==2
generated('firmware/esp32s3/main/catalog/buddy_catalog_keys.inc','/* Generated; compact ABI order is append-only. */\nstatic const char *compact_keys[] = {'+','.join(json.dumps(k) for k in wire['objectKeys'])+'};\n')
